Workflow: add px64 directory check (#9)
* Reenable VSCode build

* Add px64 directories

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,8 +19,8 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
-      # - name: Build VS Code
-      #   run: npm run gulp vscode-win32-x64-min
+      - name: Build VS Code
+        run: npm run gulp vscode-win32-x64-min
 
       - name: Package Installer
         run: npm run gulp vscode-win32-x64-system-setup
@@ -29,6 +29,7 @@ jobs:
         run: |
           echo "Checking possible build directories..."
           ls -lah ..
+          ls -lah ../px64 || echo "px64 folder not found"
           ls -lah ../p64 || echo "p64 folder not found"
           ls -lah ../VSCode-win32-x64 || echo "VSCode-win32-x64 folder not found"
 
@@ -38,7 +39,10 @@ jobs:
           name: Positron-Windows-Installer
           path: |
             ../p64/*.exe
+            ../px64/*.exe
             ../VSCode-win32-x64/*.exe
             ../VSCode-win32-x64-system-setup/*.exe
+            .build/p64/*.exe
+            .build/px64/*.exe
             .build/win32-x64/*.exe
             .build/win32-x64-system-setup/*.exe
